name: Bug
description: Report incorrect behavior in the pyventim library
title: "BUG: xxx"
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Bug report checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the latest version.
          required: true

  # Reproducible example
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example.
      placeholder: >
        import pandas as pd

        df = pd.DataFrame(range(5))

        ...
      render: python
    validations:
      required: true

  # Problem statement
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
