name: Feature
description: Suggest a new idea for this project
title: "FEATURE: xxx"
labels: [enhancement]

body:
  - type: textarea
      id: suggestion
      attributes:
        label: Suggestion
        description: >
          A summary of what you are suggesting.

      validations:
        required: true

  - type: textarea
      id: proposal
      attributes:
        label: Describe the solution you'd like
        description: >
          A with a clear and concise description of what you want to happen.

      validations:
        required: true

  - type: textarea
      id: alternatives
      attributes:
        label: Describe alternatives you've considered
        description: >
          A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
      id: additional
      attributes:
        label: Additional context
        description: >
          Describe alternatives you've considered with a clear and concise description of any alternative solutions or features you've considered.

        