
name: Release pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ##########################
  # Build the Python package
  ##########################
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v
  
  #########################
  # Build the documentation
  #########################
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build Markdown Files
  #     # You may pin to the exact commit or the version.
  #     # uses: reedjones/markdown-docs@9d6560077391af1d6e4cb251dba1e742c7f54b42
  #     uses: reedjones/markdown-docs@new

  #     with:
  #       src_path: src
  #       dst_path: docs 
     
  #   - name: Setup mdBook
  #     uses: peaceiris/actions-mdbook@v2
  #     with:
  #       mdbook-version: '0.4.10'

  #   - name: Build mdBook
  #     run: mdbook build ./docs -d ./book
    
  #   - name: Deploy mdBook
  #     uses: peaceiris/actions-gh-pages@v4
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./book
          
      
          
